// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxs4-2DWbrYdDDNYft5muf_L_oqGex4-0',
    appId: '1:398264988260:web:2a6c8c70e8faf8e129a571',
    messagingSenderId: '398264988260',
    projectId: 'tiktok-clone-396b3',
    authDomain: 'tiktok-clone-396b3.firebaseapp.com',
    storageBucket: 'tiktok-clone-396b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtCTA1r4Ak_QBxRa1JIStcoxfDra94s-I',
    appId: '1:398264988260:android:c69e1677b2e69dbd29a571',
    messagingSenderId: '398264988260',
    projectId: 'tiktok-clone-396b3',
    storageBucket: 'tiktok-clone-396b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaMSErsz8nW88a-Kgy4CLFbetugYbOSks',
    appId: '1:398264988260:ios:c523eafdeb7fbf9b29a571',
    messagingSenderId: '398264988260',
    projectId: 'tiktok-clone-396b3',
    storageBucket: 'tiktok-clone-396b3.appspot.com',
    iosClientId: '398264988260-k1gsos36c48f1r5meghlusut7qlj44nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaMSErsz8nW88a-Kgy4CLFbetugYbOSks',
    appId: '1:398264988260:ios:a2411a012d08bed529a571',
    messagingSenderId: '398264988260',
    projectId: 'tiktok-clone-396b3',
    storageBucket: 'tiktok-clone-396b3.appspot.com',
    iosClientId: '398264988260-j64ln71nlfm4d4dlqsvejcd524s3dm8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
